# Работа с библиотекой numpy

### Импортируем нужную библиотеку

In [1]:
import numpy as np

### Инициализируем массив

In [2]:
a = np.array([
    [1, 2, 3, 3, 1],
    [6, 8, 11, 10, 7]
]).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

### Задание 1. Посчитать среднее по признакам

In [3]:
mean_a = np.mean(a, axis=0)
mean_a

array([2. , 8.4])

### Задание 2. Центровка наблюдений

In [4]:
# a_centered = np.subtract(a, mean_a)
a_centered = a - mean_a
print(a_centered)
print(f'shape: {a_centered.shape}')

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]
shape: (5, 2)


### Задание 3. Ковариация признаков

Несмещенная оценка

In [5]:
a_centered_sp = a_centered[:, 0].dot(a_centered[:, 1])
a_centered_sp / (a.shape[0] - 1)

2.0

Смещенная оценка

In [6]:
a_centered_sp = a_centered[:, 0].dot(a_centered[:, 1])
a_centered_sp / (a.shape[0])

1.6

### Задание 4** Ковариация средствами numpy

Посчитаем несмещенную оценку

In [7]:
cov = np.cov(a.T, ddof=1)
cov[0, 1]

2.0

Аналогично смещенную оценку

In [8]:
cov = np.cov(a.T, ddof=0)
cov[0, 1]

1.6

# Работа с библиотекой Pandas

### Импортируем нужную библиотеку

In [9]:
import pandas as pd

### Задание 1. Инициализируем датафреймы

In [10]:
ds = np.array([[1, 2, 3], ['Тургенев', 'Чехов', 'Островский']])
authors = pd.DataFrame(data=ds.T, columns=['author_id', 'author_name'])
authors

author_id author_name
0         1    Тургенев
1         2       Чехов
2         3  Островский

In [11]:
ds = np.array([
    [1, 1, 1, 2, 2, 3, 3], 
    ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
    [450, 300, 350, 500, 450, 370, 290]
])
books = pd.DataFrame(data=ds.T, columns=['author_id', 'book_title', 'price'])
books

author_id            book_title price
0         1           Отцы и дети   450
1         1                 Рудин   300
2         1     Дворянское гнездо   350
3         2      Толстый и тонкий   500
4         2       Дама с собачкой   450
5         3                 Гроза   370
6         3  Таланты и поклонники   290

### Задание 2. Объединение датафреймов

In [12]:
authors_price = pd.merge(authors, books)
authors_price

author_id author_name            book_title price
0         1    Тургенев           Отцы и дети   450
1         1    Тургенев                 Рудин   300
2         1    Тургенев     Дворянское гнездо   350
3         2       Чехов      Толстый и тонкий   500
4         2       Чехов       Дама с собачкой   450
5         3  Островский                 Гроза   370
6         3  Островский  Таланты и поклонники   290

In [13]:
authors_price['price'] = authors_price['price'].astype(int)

### Задание 3. Топ 5 самых дорогих

In [14]:
# top5 = authors_price.sort_values(by='price', ascending=False).head(5)
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3         2       Чехов   Толстый и тонкий    500
0         1    Тургенев        Отцы и дети    450
4         2       Чехов    Дама с собачкой    450
5         3  Островский              Гроза    370
2         1    Тургенев  Дворянское гнездо    350

### Задание 4. Минимальная, максимальная и средняя цена

In [15]:
authors_stat = authors_price.copy()

max_price = authors_stat.groupby('author_name').max()['price']
max_price = max_price.to_frame(name='max')

min_price = authors_stat.groupby('author_name').min()['price']
min_price = min_price.to_frame(name='min')

mean_price = authors_stat.groupby('author_name').mean()['price']
mean_price = mean_price.to_frame(name='mean')


In [16]:
max_price

max
author_name     
Островский   370
Тургенев     450
Чехов        500

In [17]:
min_price

min
author_name     
Островский   290
Тургенев     300
Чехов        450

In [18]:
mean_price

mean
author_name            
Островский   330.000000
Тургенев     366.666667
Чехов        475.000000

In [19]:
authors_stat = pd.merge(min_price, max_price, on='author_name')
authors_stat = pd.merge(authors_stat, mean_price, on='author_name')
authors_stat

min  max        mean
author_name                      
Островский   290  370  330.000000
Тургенев     300  450  366.666667
Чехов        450  500  475.000000

### Задание 5**. Расширение датафрейма

In [20]:
authors_price_ext = authors_price.copy()
cover = pd.Series(['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'])
authors_price_ext['cover'] = cover
authors_price_ext

author_id author_name            book_title  price    cover
0         1    Тургенев           Отцы и дети    450  твердая
1         1    Тургенев                 Рудин    300   мягкая
2         1    Тургенев     Дворянское гнездо    350   мягкая
3         2       Чехов      Толстый и тонкий    500  твердая
4         2       Чехов       Дама с собачкой    450  твердая
5         3  Островский                 Гроза    370   мягкая
6         3  Островский  Таланты и поклонники    290   мягкая

In [21]:
book_info = pd.pivot_table(authors_price_ext, index=['author_name'], columns=['cover'], values=['price'])
book_info = book_info.fillna(value=0)
book_info

price        
cover       мягкая твердая
author_name               
Островский   330.0     0.0
Тургенев     325.0   450.0
Чехов          0.0   475.0

In [22]:
book_info.to_pickle('book_info.pkl')

In [23]:
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

price        
cover       мягкая твердая
author_name               
Островский   330.0     0.0
Тургенев     325.0   450.0
Чехов          0.0   475.0

Сравним два датафрейма с помощью метода _compare_

In [24]:
book_info.compare(book_info2, keep_shape=True, keep_equal=True)

price                      
cover       мягкая        твердая       
              self  other    self  other
author_name                             
Островский   330.0  330.0     0.0    0.0
Тургенев     325.0  325.0   450.0  450.0
Чехов          0.0    0.0   475.0  475.0